# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Update checkout from v4 to v4.2.2 (or the latest v4 minor patch)
      - name: Checkout Code
        uses: actions/checkout@v4.2.2 

    # 2. Update setup-java to version 4.7.0 or higher
      - name: Set up Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu'
          java-version: '17'

    # 3. Update the subosito flutter action if needed
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: 'stable'
        
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter Web Release
        run: flutter build web --release --base-href "/EliteShoppe/"

      # Automates uploading the build/web folder to a isolated "gh-pages" branch
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web 
          branch: gh-pages  
      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
